#!/bin/bash

COMPILER="clang"
LIBSOUNDIO_RELATIVE_PATH="libsoundio-1.1.0"
CURRENT_DIRECTORY=`pwd`
BUILD_DIRECTORY=$CURRENT_DIRECTORY/libsoundio_build
rm -rf $BUILD_DIRECTORY
mkdir -p $BUILD_DIRECTORY
SOURCE_DIRECTORY="$(cd `dirname $0` && pwd)/$LIBSOUNDIO_RELATIVE_PATH"
echo "source directory: $SOURCE_DIRECTORY"
echo "build directory: $BUILD_DIRECTORY"
INSTALL_DIRECTORY="$CURRENT_DIRECTORY/libs/libsoundio/"
echo "install prefix: $INSTALL_DIRECTORY"
rm -rf $INSTALL_DIRECTORY

cd $BUILD_DIRECTORY

CC=$COMPILER cmake $SOURCE_DIRECTORY -DCMAKE_BUILD_TYPE=debug -DBUILD_STATIC_LIBS=ON -DBUILD_EXAMPLE_PROGRAMS=OFF -DBUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=$INSTALL_DIRECTORY -DCMAKE_INSTALL_LIBDIR=lib && \
make -j8 && \
make install && \
rm $INSTALL_DIRECTORY/lib/*.so* # HACK: remove shared library to force linker to link to static
