#!/bin/bash

QT_VERSION=6.8.1
INSTALLER_FRAMEWORK_VERSION=4.8

QT_INSTALL_PATH=/e/Qt

QT_PATH=$QT_INSTALL_PATH/$QT_VERSION/mingw_64/
TOOLCHAIN_PATH=$QT_INSTALL_PATH/Tools/mingw1310_64/bin
INSTALLER_FRAMEWORK_PATH=$QT_INSTALL_PATH/Tools/QtInstallerFramework/$INSTALLER_FRAMEWORK_VERSION/bin

export PATH=$PATH:$TOOLCHAIN_PATH:$QT_PATH/bin/:$INSTALLER_FRAMEWORK_PATH

echo -e "Qt path:\t$QT_PATH"
echo -e "Toolchain:\t$TOOLCHAIN_PATH"
echo -e "Installer:\t$INSTALLER_FRAMEWORK_PATH"
