on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-24.04
    concurrency:
      group: omnipackage-${{ inputs.repository }}
      cancel-in-progress: false

    steps:
      - name: Install omnipackage
        run: |
          echo 'deb https://repositories.omnipackage.org/omnipackage-rs/master/ubuntu_24.04 stable/' | sudo tee /etc/apt/sources.list.d/omnipackage_omnipackage.list
          curl -fsSL https://repositories.omnipackage.org/omnipackage-rs/master/ubuntu_24.04/stable/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/omnipackage_omnipackage.gpg > /dev/null
          sudo apt-get update
          sudo apt-get install omnipackage

      - uses: actions/checkout@v6

      - run: echo "${{ secrets.OMNIPACKAGE_MPZ_DOTENV }}" > .env

      - run: omnipackage release . --container-output null --repository "${{ inputs.repository }}"