on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      version_extractor:
        required: true
        type: string
      image_cache:
        required: true
        type: string
      runs_on:
        required: true
        type: string
      skip_distros:
        required: false
        type: string
        default: '[]'

jobs:
  list-distros:
    runs-on: ubuntu-latest
    outputs:
      distros: ${{ steps.get-distros.outputs.distros }}
    steps:
      - uses: omnipackage/omnipackage-rs@master
      - uses: actions/checkout@v6
      - name: Get distro list
        id: get-distros
        env:
          SKIP: ${{ inputs.skip_distros }}
        run: |
          all=$(omnipackage info --list-distros . --format json)
          echo "distros=$(jq -cn --argjson all "$all" --argjson skip "$SKIP" '$all - $skip')" >> "$GITHUB_OUTPUT"

  release:
    needs: [list-distros]
    runs-on: ${{ inputs.runs_on }}
    concurrency:
      group: omnipackage-${{ inputs.repository }}-${{ matrix.distro }}
      cancel-in-progress: false
    strategy:
      fail-fast: false
      matrix:
        distro: ${{ fromJson(needs.list-distros.outputs.distros) }}
    steps:
      - uses: omnipackage/omnipackage-rs@master
      - uses: actions/checkout@v6
      - run: echo "${{ secrets.OMNIPACKAGE_MPZ_DOTENV }}" > .env
      - name: Release packages for ${{ matrix.distro }}
        run:  omnipackage release . --build-dir $RUNNER_TEMP --repository "${{ inputs.repository }}" --distros "${{ matrix.distro }}" --version-extractor "${{ inputs.version_extractor }}" --image-cache "${{ inputs.image_cache }}"
