name: OmniPackage master aka next

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  publish:
    uses: ./.github/workflows/_omnipackage.yml
    with:
      repository: "Cloudflare R2 next"