name: OmniPackage build and publish

on:
  workflow_dispatch:
  # push:
  #  branches: [ main ]


jobs:
  run:
    runs-on: ubuntu-latest
    concurrency:
      group: omnipackage
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4

      - run: echo "${{ secrets.OMNIPACKAGE_MPZ_DOTENV }}" > .env

      - uses: omnipackage/omnipackage-rs/.github/actions/setup@master
        with:
          version: master

      - run: omnipackage release --fail-fast .