name: OmniPackage stable

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    uses: ./.github/workflows/_omnipackage.yml
    with:
      repository: "Cloudflare R2 stable"