name: AUR push package

on: push

jobs:
  aur_push:

    runs-on: ubuntu-latest

    steps:
    - name: Sleep for 30 seconds (wait for master.zip)
      uses: whatnick/wait-action@master
      with:
        time: '30s'

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Run release script
      env:
        AUR_SSH_PRIVATE_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
      run: ./release-aur-github-action.rb
