name: Image cache refresh

on:
  workflow_dispatch:
  schedule:
    - cron: '44 6 1 * *'

permissions:
  packages: write

jobs:
  x86_64:
    uses: ./.github/workflows/_refresh-omnipackage-cache.yml
    secrets: inherit
    with:
      arch: "x86_64"
      runs_on: "ubuntu-24.04"

  aarch64:
    uses: ./.github/workflows/_refresh-omnipackage-cache.yml
    secrets: inherit
    with:
      arch: "aarch64"
      runs_on: "ubuntu-24.04-arm"
      # arch: no arm64 image. manjaro: Manjaro ARM repos frozen ~2024
      skip_distros: '["arch", "manjaro"]'
