name: Release AUR package

on: push

jobs:
  release_aur_package:
    runs-on: ubuntu-latest

    steps:
    - name: Sleep (wait for master.zip)
      run: sleep 42

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Run release script
      env:
        AUR_SSH_PRIVATE_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
      run: ./.github/release-aur-github-action.rb
